services:
  - type: web
    name: app-feedback
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_CLOUD_CREDENTIALS
        sync: false  # This means you'll set it manually in Render dashboard
